import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense>
      <html lang="en">
        <body className="flex">
          <nav className="bg-gray-200 p-4">
            <Link href={`/`}>Home</Link>

            {Array.from(Array(10).keys()).map((i) => (
              <Link href={`/post/${i}`} key={i}>
                <p>Page {i}</p>
              </Link>
            ))}
          </nav>
          <main className="p-4">{children}</main>
        </body>
      </html>
    </Suspense>
  );
}
